//number
//string => ""
//boolean => true/false
//null
// undifines
// object

const name="pushkar"
let age;
//console.log(name);

// console.log(typeof "pushkar");
// console.log(typeof name);
// console.log(typeof (name)); // same

// console.log(typeof null); // type of null is object
// console.log(typeof undefined); // type of undifined is undefined
// console.log(typeof age) // type of age is undifined


